version: '3.3'

services:
  database:
    image: mongo:latest
    restart: unless-stopped

  back-end:
    image: noname120hz/api-back-end:1.1.0-port443
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - database
    environment:
      MONGO_IP: database

  front-end:
    image: noname120hz/api-front-end:1.2.1-port443
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - back-end

